# Antigua Entrega 2

Entrega 2
Antecedentes, marco teórico e hipótesis



Con base en el problema de investigación planteado en la entrega anterior, y luego de haber realizado las correcciones y/o modificaciones indicadas por el docente, trate de avanzar en los siguientes ítems:

1-) Elaboración de los antecedentes de investigación:

La redacción de antecedentes de investigación consiste en un trabajo de revisión de la bibliografía de la temática escogida, a través del cual se nuclea algunas investigaciones y experiencias previas, exponiendo líneas de investigación y debates sobre el tema elegido. Para su elaboración deberán articular los textos seleccionado y leídos, buscando elaborar un argumento que les permita insertar su propio estudio en un área o campo de investigación más general. Para ello:

Presenten la temática específica que aborda cada artículo seleccionado. En principio, la temática no debería variar demasiado entre los artículos seleccionados. Si consideran que varían mucho, puede ser una alternativa (re)considerar la selección de los artículos.

Indiquen las principales líneas teóricas y metodológicas que siguen los artículos. En este punto, a diferencia del punto I, efectivamente se esperan mayores variaciones entre los artículos seleccionados.
Resalten los hallazgos empíricos más relevantes a los que estos trabajos han arribado.
Al final, en la sección de bibliografía, listen todos los estudios consultados.






Selección del marco teórico:

Defina su enfoque teórico. ¿Cuáles son los principales supuestos y conceptos que orientarán su investigación? Elaboren un texto breve el cual de cuenta del marco teórico de su investigación, es decir, en qué lugar se ubica el investigador para abordar su objeto de estudio. Incorporen bibliografía en la que se encuentren las definiciones de los conceptos centrales del estudio.


Nota: Tengan en cuenta que el marco teórico se diferencia de los antecedentes. Si bien en ambos el investigador se basa en hallazgos y afirmaciones de otros trabajos, en los antecedentes el investigador presenta de manera general el área temática de la cual se desprende su estudio y los (posiblemente variados) marcos teóricos que existen en ese campo. En cambio, el marco teórico seleccionado, se acota a la propia perspectiva teórica que elige el investigador para (intentar) dar respuesta a sus preguntas y objetivos.

Objetivos:

Redefinan sus preguntas y objetivos de investigación considerando los avances en la construcción del problema y su articulación con el marco teórico.


Hipótesis:

Formulen la hipótesis principal que da respuesta a su pregunta/problema de investigación. Recuerden que esta debe articularse con la perspectiva propuesta en el marco teórico.

