# Antigua Entrega 6

Entrega 6
Presentación del informe de la investigación


El trabajo práctico final consiste en la presentación de un informe de investigación donde conste:

TEMA/PROBLEMA DE INVESTIGACIÓN PLANTEADO (Describir en qué contexto temporal y espacial se encuentra el problema que se propone investigar y los límites disciplinares sobre los cuales tienen validez sus hallazgos)
OBJETIVOS E HIPÓTESIS DE INVESTIGACIÓN. (Identifique si se desea ampliar/refutar un conocimiento existente y formule una o más hipótesis sobre lo que espera descubrir o refutar)
DEBATE TEÓRICO O JUSTIFICACIÓN DEL PROBLEMA. (Seleccione el marco teórico o los supuestos ideológicos que orientan o justifican su investigación)
DISEÑO DE LA INVESTIGACIÓN (Describa el tipo de diseño, la muestra, los indicadores utilizados, etc.)
PRESENTACIÓN Y ANÁLISIS DE RESULTADOS. (Se trata de presentar la información de manera organizada bajo la forma de evidencia que avalen o refuten las hipótesis o supuestos en discusión).
CONCLUSIONES. (Se trata de resumir lo hecho y lo descubierto, pero desde el sujeto que investiga. Es posible tomar posición frente a la evidencia 10producida, a favor o en contra, y proponer/imaginar nuevos caminos.)



Formato de presentación:

Trabajo grupal de una extensión aproximada de 10 carillas (sin incluir carátula ni bibliografía y anexo de cuadros), letra arial 11 o similar, hoja A4, márgenes de 3 cm., interlineado 1 ½.
Enviar el trabajo por mail a la casilla del docente y también presentarlo impreso.
Junto con la entrega del informe de investigación cada grupo deberá exponer su investigación de acuerdo a las indicaciones de su docente.
